2024-09-23 23:46:51,660 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-23 23:46:51,914 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-23 23:46:51,914 - apscheduler.scheduler - INFO - Scheduler started
2024-09-23 23:46:51,914 - telegram.ext.Application - INFO - Application started
2024-09-23 23:46:53,286 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:46:53,301 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-23 23:46:53,779 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-23 23:46:58,385 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:46:58,385 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-23 23:46:59,360 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-23 23:47:09,166 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:47:19,818 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:47:30,161 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:47:40,328 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:47:51,454 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:48:01,978 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:48:12,132 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:48:23,741 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:48:33,921 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:48:44,846 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:48:55,195 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:49:05,422 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:49:15,990 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:49:26,431 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:49:36,686 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:49:46,889 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:49:58,141 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:50:08,587 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:50:18,999 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:50:29,218 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:50:39,494 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:50:50,270 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:51:01,981 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:51:12,570 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:51:24,028 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:51:34,949 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:51:45,935 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:51:56,305 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:52:06,469 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:52:17,230 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:52:27,405 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:52:38,526 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:52:48,674 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:52:59,246 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:53:09,467 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:53:19,688 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:53:29,942 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:53:40,845 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:53:51,211 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:54:03,031 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:54:13,359 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:54:23,570 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:54:33,823 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:54:44,009 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:54:50,225 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-23 23:54:50,682 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-23 23:54:50,682 - apscheduler.scheduler - INFO - Scheduler started
2024-09-23 23:54:50,682 - telegram.ext.Application - INFO - Application started
2024-09-23 23:54:59,299 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:54:59,314 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-23 23:55:00,220 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-23 23:55:06,289 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:55:06,289 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-23 23:55:07,451 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-23 23:55:16,472 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:55:27,210 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:55:37,196 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-23 23:55:37,366 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-23 23:55:37,366 - apscheduler.scheduler - INFO - Scheduler started
2024-09-23 23:55:37,366 - telegram.ext.Application - INFO - Application started
2024-09-23 23:55:38,372 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:55:38,388 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-23 23:55:39,517 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-23 23:55:49,708 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:55:59,975 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:56:10,176 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:56:21,339 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:56:31,545 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:56:42,589 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-23 23:56:42,737 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-23 23:56:42,737 - apscheduler.scheduler - INFO - Scheduler started
2024-09-23 23:56:42,737 - telegram.ext.Application - INFO - Application started
2024-09-23 23:56:44,068 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:56:44,068 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-23 23:56:44,433 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-23 23:56:54,360 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:57:05,006 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:57:15,504 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:57:25,929 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:57:36,076 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:57:46,330 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:57:57,311 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:58:06,466 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:58:09,085 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-23 23:58:09,085 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 78, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long
2024-09-23 23:58:16,907 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:58:27,189 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:58:37,503 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:58:46,302 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:58:47,929 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-23 23:58:47,929 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 78, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long
2024-09-23 23:58:48,757 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:58:48,757 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-23 23:58:49,143 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-23 23:58:59,322 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:59:09,600 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:59:19,864 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:59:30,517 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:59:40,795 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-23 23:59:51,413 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:00:02,079 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:00:12,328 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:00:22,565 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:00:32,788 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:00:42,973 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:00:45,850 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:00:46,019 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:00:46,019 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:00:46,019 - telegram.ext.Application - INFO - Application started
2024-09-24 00:00:49,454 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:00:51,668 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:00:51,668 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 78, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long
2024-09-24 00:01:00,024 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:01:10,392 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:01:21,442 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:01:28,162 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:01:28,820 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:01:28,820 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:01:28,820 - telegram.ext.Application - INFO - Application started
2024-09-24 00:01:35,666 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:01:35,666 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:01:36,349 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:01:38,400 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:01:39,205 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:01:39,205 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 35, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long
2024-09-24 00:01:48,850 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:01:59,059 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:02:09,326 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:02:19,865 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:02:30,257 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:02:40,539 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:02:51,141 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:03:01,409 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:03:11,594 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:03:21,816 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:03:32,041 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:03:42,267 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:03:49,346 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:03:49,500 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:03:49,500 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:03:49,500 - telegram.ext.Application - INFO - Application started
2024-09-24 00:03:53,607 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:03:56,588 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:03:56,588 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 36, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:03:58,872 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:03:58,881 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:03:59,160 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:04:02,827 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:04:04,724 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:04:04,724 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 36, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:04:14,726 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:04:25,149 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:04:35,376 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:04:45,638 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:04:56,071 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:05:07,247 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:05:17,624 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:05:28,133 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:05:38,874 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:05:49,516 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:05:59,817 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:06:10,235 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:06:20,395 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:06:30,683 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:06:57,289 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:07,707 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:18,062 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:20,503 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:07:20,692 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:07:20,692 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:07:20,692 - telegram.ext.Application - INFO - Application started
2024-09-24 00:07:23,565 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:26,498 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:07:26,498 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 39, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:07:26,951 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:26,953 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758, Time: 2024-09-24 00:07:26
2024-09-24 00:07:27,665 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:07:29,570 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:29,570 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758, Time: 2024-09-24 00:07:29
2024-09-24 00:07:29,904 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:07:33,437 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:36,285 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:07:36,285 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 39, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:07:37,436 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:37,438 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758, Time: 2024-09-24 00:07:37
2024-09-24 00:07:38,018 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:07:47,868 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:58,482 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:59,466 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:07:59,466 - __main__ - INFO - User: Ismoilova Mahbuba None, Username: @Ismoilova_M_X, User ID: 1527780675, Time: 2024-09-24 00:07:59
2024-09-24 00:08:00,633 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:08:08,322 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:08:08,322 - __main__ - INFO - User: Ismoilova Mahbuba None, Username: @Ismoilova_M_X, User ID: 1527780675, Time: 2024-09-24 00:08:08
2024-09-24 00:08:08,981 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:08:18,620 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:08:24,630 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:08:26,696 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:08:26,696 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 39, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:08:28,253 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:08:28,253 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758, Time: 2024-09-24 00:08:28
2024-09-24 00:08:28,453 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:08:31,094 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:08:35,010 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:08:35,010 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 39, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:08:43,128 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:08:53,381 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:08:59,149 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:09:01,100 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:09:01,101 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 39, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:09:09,373 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:09:20,655 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:09:30,889 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:09:41,177 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:09:51,450 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:10:02,208 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:10:02,532 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:10:02,532 - __main__ - INFO - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758, Time: 2024-09-24 00:10:02
2024-09-24 00:10:03,166 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:10:04,499 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:10:04,499 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 39, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:10:05,175 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:10:07,085 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:10:07,085 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 39, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:10:16,982 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:10:27,433 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:10:38,067 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:10:48,481 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:10:58,709 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:11:08,916 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:11:19,093 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:11:29,319 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:11:39,488 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:11:49,825 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:11:59,967 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:12:10,451 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:12:20,819 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:12:31,364 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:12:41,571 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:15:02,608 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:15:02,840 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:15:02,840 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:15:02,840 - telegram.ext.Application - INFO - Application started
2024-09-24 00:15:03,757 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:15:03,757 - __main__ - INFO - 2024-09-24 00:15:03 - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:15:04,090 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:15:10,410 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:15:10,410 - __main__ - INFO - 2024-09-24 00:15:10 - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:15:11,720 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:15:15,599 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:15:18,245 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:15:18,245 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 35, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:15:21,534 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:15:21,534 - __main__ - INFO - 2024-09-24 00:15:21 - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:15:21,751 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:15:27,060 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:15:27,300 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:15:27,300 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:15:27,300 - telegram.ext.Application - INFO - Application started
2024-09-24 00:15:33,982 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:15:34,188 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:15:34,190 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:15:34,190 - telegram.ext.Application - INFO - Application started
2024-09-24 00:15:41,727 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:15:41,926 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:15:41,928 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:15:41,928 - telegram.ext.Application - INFO - Application started
2024-09-24 00:15:44,444 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:15:47,587 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:15:47,588 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 35, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:15:55,247 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:16:05,479 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:16:16,019 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:16:26,814 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:16:33,681 - httpx - INFO - HTTP Request: POST https://api.telegram.org/botYOUR_TOKEN_HERE/getMe "HTTP/1.1 404 Not Found"
2024-09-24 00:17:17,982 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:17:18,114 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:17:18,114 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:17:18,114 - telegram.ext.Application - INFO - Application started
2024-09-24 00:17:18,670 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:17:21,181 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:17:21,181 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 35, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:17:29,093 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:17:35,412 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:17:35,646 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:17:35,648 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:17:35,648 - telegram.ext.Application - INFO - Application started
2024-09-24 00:17:37,400 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:17:38,841 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:17:40,433 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:17:40,433 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 35, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:17:40,449 - __main__ - INFO - 2024-09-24 00:17:40 - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:17:40,889 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:17:43,501 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:17:43,501 - __main__ - INFO - 2024-09-24 00:17:43 - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:17:44,068 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:17:47,238 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:17:48,647 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:17:48,647 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 35, in show_users
    await update.message.reply_text(logs)
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:17:58,072 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:18:08,294 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:18:18,525 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:18:28,798 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:18:39,032 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:18:49,627 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:18:59,832 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:19:10,054 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:19:20,253 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:19:30,524 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:21:33,064 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:21:33,281 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:21:33,281 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:21:33,281 - telegram.ext.Application - INFO - Application started
2024-09-24 00:21:39,853 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:21:42,777 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:21:42,777 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 34, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:21:47,467 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:21:47,468 - __main__ - INFO - 2024-09-24 00:21:47 - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:21:47,808 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:21:50,502 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:21:52,397 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:21:52,397 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 34, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:22:02,223 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:22:12,832 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:22:23,528 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:22:29,572 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:22:30,459 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:22:40,012 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:22:50,487 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:22:55,016 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:22:55,016 - __main__ - INFO - 2024-09-24 00:22:55 - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:22:55,952 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:23:00,062 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:23:00,062 - __main__ - INFO - 2024-09-24 00:23:00 - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:23:00,417 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:23:10,129 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:23:10,252 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:23:10,252 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:23:10,252 - telegram.ext.Application - INFO - Application started
2024-09-24 00:23:11,289 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:23:11,289 - __main__ - INFO - 2024-09-24 00:23:11 - User: Laz1zbek_Quvondiqov None, Username: @Lazizbek_Quvondiqov, User ID: 1205534758
2024-09-24 00:23:11,712 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:23:16,435 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:23:20,895 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:23:20,895 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 34, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:23:27,375 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:23:38,408 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:23:48,673 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:23:49,579 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:23:53,870 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:23:53,870 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 34, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:23:59,908 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:24:04,652 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:24:04,652 - __main__ - INFO - 2024-09-24 00:24:04 - User: Ismoilova Mahbuba None, Username: @Ismoilova_M_X, User ID: 1527780675
2024-09-24 00:24:05,410 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 200 OK"
2024-09-24 00:24:11,560 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:24:15,855 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:24:15,855 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 34, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:24:21,838 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:24:31,984 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:24:42,211 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:24:52,445 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:25:02,681 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:25:12,949 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:25:23,268 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:25:33,724 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:25:43,983 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:25:54,240 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:25:57,261 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getMe "HTTP/1.1 200 OK"
2024-09-24 00:25:57,431 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/deleteWebhook "HTTP/1.1 200 OK"
2024-09-24 00:25:57,431 - apscheduler.scheduler - INFO - Scheduler started
2024-09-24 00:25:57,431 - telegram.ext.Application - INFO - Application started
2024-09-24 00:26:00,686 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:26:02,917 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/sendMessage "HTTP/1.1 400 Bad Request"
2024-09-24 00:26:02,917 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_application.py", line 1335, in process_update
    await coroutine
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/bekmu/AppData/Local/Programs/Python/Python311/m.bot.py", line 36, in show_users
    await update.message.reply_text(logs or "Hech qanday foydalanuvchi ma'lumotlari yo'q.")
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_message.py", line 1762, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 2909, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 1029, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 610, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 745, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bekmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\request\_baserequest.py", line 382, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-09-24 00:26:11,286 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:26:21,477 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:26:31,623 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:26:42,012 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:26:52,194 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:27:02,434 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:27:12,745 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:27:23,027 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:27:33,518 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:27:43,830 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:27:55,353 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:28:09,944 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:28:20,519 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:28:30,757 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:28:40,977 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:28:51,237 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:29:01,472 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
2024-09-24 00:29:11,703 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7232918320:AAF1VenP8qry_1r-NEJWjSwBO4eJauCk6Xk/getUpdates "HTTP/1.1 200 OK"
